### PR TITLE
Stage 3 - complete

### PR DESCRIPTION
**Pull request by mohfez**
Some parts of stage 3 completed.

### CODE REVIEW

**Comment by Deadly-Pigg** [comment]
please merge this soon so that it doesn't become too outdated

**Comment by Deadly-Pigg** [comment]
I tested it, and it seems to be fully working. Good to merge.

**Comment by VictorVictini** [comment]
thanks

**Comment by VictorVictini** [comment]
I'll fix the conflicts then merge it

**Review by VictorVictini — COMMENTED** [review]
lgtm

**Pull request merged**
