### PR TITLE
stages 7 and 8

### PR DESCRIPTION
**Pull request by VictorVictini**
Most of it seems fine, untested functionality with history (as that branch hasn't been merged yet)
Parsing with parse_alias_line could include token parsing instead of only checking for ' '
Could include a format check on parse_alias_line that would consequently check the format for read_alias_file

### CODE REVIEW

**Comment by VictorVictini** [comment]
made parse_alias_line enforce a format

**Comment by VictorVictini** [comment]
one possible addition is to allow any number of spaces (/tokens) after using `alias` as it currently assumes only 1

**Comment by VictorVictini** [comment]
Additionally, it may be arguable whether to support all tokens in parse_alias_line or simply spaces

**Comment by Deadly-Pigg** [comment]
image
amazing

**Comment by Deadly-Pigg** [comment]
Latest branch is completely broken. Saving to alias doesn't even work properly since it saves __everything__ after the 'alias' part as the name.
Closing the shell then reopening it seems to 'duplicate' the text in the aliases file, and also delete a character from them, too. After doing this enough, it causes the program to fail to read from the file (obviously)

**Comment by Deadly-Pigg** [comment]
Older branch seems to work a bit better, but still have their own fair share of issues (i.e, the character deletion when saving/loading).

**Comment by VictorVictini** [comment]
oops

**Comment by VictorVictini** [comment]
these should fix the two issues listed, if there's an edge case I haven't found please let me know

**Comment by VictorVictini** [comment]
does the order of the aliases matter? if they do, it may be required to change how remove_alias is handled (currently it swaps the alias to be removed with the last alias, then sets the last one to be empty, in one 'move' for efficiency reasons)

**Comment by Deadly-Pigg** [comment]
Looks good to me. Just needs history to be included (at some point) but otherwise good enough

**Pull request merged**
