### PR TITLE
file handling refactor for alias and history

### PR DESCRIPTION
**Pull request by VictorVictini**
made the file handling more robust

used the following cases to test it:
- empty file
- file with overwriting alias (e.g. same alias again and again) for 11+ lines
- file with no overwriting alias but 11+ lines
- file with normal lines
- corrupted file lines (shouldn't be an issue, unchanged afaik)
- file does not exist

### CODE REVIEW

**Comment by VictorVictini** [comment]
additional note: we support overwriting aliases within the file e.g.
```
a b
a c
```
would result in 1 alias being created which is `a` linking to `c`

**Comment by VictorVictini** [comment]
given the deadline is approaching, would appreciate this being checked asap -- it should work as expected tho

the test cases for history are:
- file not existing
- too many lines in file (>20)
- empty file
- normal file

**Comment by VictorVictini** [comment]
in any case of the history/alias erroring, their lengths are set to 0 mimicking a clear
it could be more robust by clearing it, but that seems unnecessary
could consider remaking remove_alias so it doesn't set the last alias' details to '\0' -- seeing as the length handles what actually gets checked

**Comment by VictorVictini** [comment]
additional test case:
- a single line exceeding the buffer limits

**Review by mohfez — APPROVED** [review]
yep, yep, yep, good code

lgtm

**Comment by mohfez** [comment]
Boss, you can merge now.

**Comment by Deadly-Pigg** [comment]
boss please merge. You have got my approval boss.
lgtv

**Review by Deadly-Pigg — APPROVED** [review]
good code good code good code

**Comment by VictorVictini** [comment]
ok ill merge bosses

**Pull request merged**
